using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;

namespace Pandit_Application
{
    public class Mail
    {

        public static int SendMailforMeeting(string To, string Subject, string Message)
        {

          
            int res = 0;
            string from = "admin@astrohouz.com";
            string password = "admin@123astrohouz";
            string hostName = "relay-hosting.secureserver.net";
            string Port = "25";
            int PortNumber = Convert.ToInt32(Port);
            string css = "";

            //Go Daddy Mail Code
            //MailMessage mm = new MailMessage(from, To);
            //mm.CC.Add("iamragini31@gmail.com");
            //if (Bcc != "")
            //{
            //    mm.Bcc.Add(Bcc);
            //}
            //mm.Subject = Subject;
            //mm.Body = Message;
            //mm.IsBodyHtml = true;
            //SmtpClient smtp = new System.Net.Mail.SmtpClient(hostName, PortNumber);
            //smtp.EnableSsl = false;
            //smtp.Credentials = new System.Net.NetworkCredential(from, password);
            //smtp.UseDefaultCredentials = true;
            //smtp.Send(mm);

            ////Gmail message code
            //MailMessage message = new MailMessage();
            //long LoginId = Convert.ToInt64(HttpContext.Current.Session["Ecode"].ToString());
            //message.From = new MailAddress(from);
            //message.To.Add(new MailAddress(To));
            //message.Subject = "Meeting has been scheduled on " + StartDate + "";
            //message.Body = "Dear " + VisitorName + "This is to inform that meeting has been scheduled on " + StartDate + " at " + StartTime + " .<br /><br />Futher Details Has been mentioned below :<br /><br /> From:" + StartDate + " TO: " + EndTime + "<br /><br />Meeing Purpose : " + MeetingPurpose + " <br />Regards<br />*** This email was auto-generated by HRMS Portal. Please do not reply to this email *** ";
            //message.IsBodyHtml = true;
            //var smtp = new System.Net.Mail.SmtpClient();
            //{
            //    smtp.Host = "smtp.gmail.com";
            //    smtp.Port = 587;
            //    smtp.EnableSsl = true;
            //    smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
            //    smtp.Credentials = new NetworkCredential(from, password);
            //    smtp.Timeout = 20000;
            //}
            //// send email
            //smtp.Send(message);K93bhgu5rzg-eMaMjYyNgwb64QOgyu4QNxFnNymfwY
            return res = 1;
        }
    }
}